"""Add avatar_url to user

Revision ID: 310fa59e1d1f
Revises: 740e728c4345
Create Date: 2025-05-18 23:21:35.934657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310fa59e1d1f'
down_revision = '740e728c4345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
