version: '3.8'
services:
  flask:
    build: ./app
    container_name: terracore-flask
    ports:
      - "5050:5000"
    volumes:
      - ./app:/app
      - ./gunicorn.conf.py:/app/gunicorn.conf.py  # Mount gunicorn config from project root
    restart: unless-stopped
    environment:
      OAUTHLIB_INSECURE_TRANSPORT: "1"

volumes:
  mysql_data: